<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            // 11 Aceh
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Barat',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Barat Daya',        'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Besar',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Jaya',              'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Selatan',           'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Singkil',           'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Tamiang',           'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Tengah',            'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Tenggara',          'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Timur',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Aceh Utara',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Bener Meriah',           'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Bireuen',                'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Gayo Lues',              'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Nagan Raya',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Pidie',                  'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Pidie Jaya',             'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kabupaten Simeulue',               'type' => 'KABUPATEN'],
            ['province_code' => '11', 'name' => 'Kota Banda Aceh',                  'type' => 'KOTA'],
            ['province_code' => '11', 'name' => 'Kota Langsa',                      'type' => 'KOTA'],
            ['province_code' => '11', 'name' => 'Kota Lhokseumawe',                 'type' => 'KOTA'],
            ['province_code' => '11', 'name' => 'Kota Sabang',                      'type' => 'KOTA'],
            ['province_code' => '11', 'name' => 'Kota Subulussalam',                'type' => 'KOTA'],
            // 12 Sumatera Utara
            ['province_code' => '12', 'name' => 'Kabupaten Asahan',                 'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Batu Bara',              'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Dairi',                  'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Deli Serdang',           'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Humbang Hasundutan',     'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Karo',                   'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Labuhanbatu',            'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Labuhanbatu Selatan',    'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Labuhanbatu Utara',      'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Langkat',                'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Mandailing Natal',       'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Nias',                   'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Nias Barat',             'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Nias Selatan',           'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Nias Utara',             'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Padang Lawas',           'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Padang Lawas Utara',     'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Pakpak Bharat',          'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Samosir',                'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Serdang Bedagai',        'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Simalungun',             'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Tapanuli Selatan',       'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Tapanuli Tengah',        'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Tapanuli Utara',         'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kabupaten Toba',                   'type' => 'KABUPATEN'],
            ['province_code' => '12', 'name' => 'Kota Binjai',                      'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Gunungsitoli',                'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Medan',                       'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Padangsidimpuan',             'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Pematangsiantar',             'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Sibolga',                     'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Tanjungbalai',                'type' => 'KOTA'],
            ['province_code' => '12', 'name' => 'Kota Tebing Tinggi',               'type' => 'KOTA'],
            // 13 Sumatera Barat
            ['province_code' => '13', 'name' => 'Kabupaten Agam',                   'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Dharmasraya',            'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Kepulauan Mentawai',     'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Lima Puluh Kota',        'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Padang Pariaman',        'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Pasaman',                'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Pasaman Barat',          'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Pesisir Selatan',        'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Sijunjung',              'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Solok',                  'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Solok Selatan',          'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kabupaten Tanah Datar',            'type' => 'KABUPATEN'],
            ['province_code' => '13', 'name' => 'Kota Bukittinggi',                 'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Padang',                      'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Padang Panjang',              'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Pariaman',                    'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Payakumbuh',                  'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Sawahlunto',                  'type' => 'KOTA'],
            ['province_code' => '13', 'name' => 'Kota Solok',                       'type' => 'KOTA'],
            // 14 Riau
            ['province_code' => '14', 'name' => 'Kabupaten Bengkalis',              'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Indragiri Hilir',        'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Indragiri Hulu',         'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Kampar',                 'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Kepulauan Meranti',      'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Kuantan Singingi',       'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Pelalawan',              'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Rokan Hilir',            'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Rokan Hulu',             'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kabupaten Siak',                   'type' => 'KABUPATEN'],
            ['province_code' => '14', 'name' => 'Kota Dumai',                       'type' => 'KOTA'],
            ['province_code' => '14', 'name' => 'Kota Pekanbaru',                   'type' => 'KOTA'],
            // 15 Jambi
            ['province_code' => '15', 'name' => 'Kabupaten Batanghari',             'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Bungo',                  'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Kerinci',                'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Merangin',               'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Muaro Jambi',            'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Sarolangun',             'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Tanjung Jabung Barat',   'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Tanjung Jabung Timur',   'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kabupaten Tebo',                   'type' => 'KABUPATEN'],
            ['province_code' => '15', 'name' => 'Kota Jambi',                       'type' => 'KOTA'],
            ['province_code' => '15', 'name' => 'Kota Sungaipenuh',                 'type' => 'KOTA'],
            // 16 Sumatera Selatan
            ['province_code' => '16', 'name' => 'Kabupaten Banyuasin',              'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Empat Lawang',           'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Lahat',                  'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Muara Enim',             'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Musi Banyuasin',         'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Musi Rawas',             'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Musi Rawas Utara',       'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Ogan Ilir',              'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Ogan Komering Ilir',     'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Ogan Komering Ulu',      'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Ogan Komering Ulu Selatan', 'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Ogan Komering Ulu Timur',   'type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kabupaten Penukal Abab Lematang Ilir','type' => 'KABUPATEN'],
            ['province_code' => '16', 'name' => 'Kota Lubuklinggau',                'type' => 'KOTA'],
            ['province_code' => '16', 'name' => 'Kota Pagar Alam',                  'type' => 'KOTA'],
            ['province_code' => '16', 'name' => 'Kota Palembang',                   'type' => 'KOTA'],
            ['province_code' => '16', 'name' => 'Kota Prabumulih',                  'type' => 'KOTA'],
            // 17 Bengkulu
            ['province_code' => '17', 'name' => 'Kabupaten Bengkulu Selatan',       'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Bengkulu Tengah',        'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Bengkulu Utara',         'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Kaur',                   'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Kepahiang',              'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Lebong',                 'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Mukomuko',               'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Rejang Lebong',          'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kabupaten Seluma',                 'type' => 'KABUPATEN'],
            ['province_code' => '17', 'name' => 'Kota Bengkulu',                    'type' => 'KOTA'],
            // 18 Lampung
            ['province_code' => '18', 'name' => 'Kabupaten Lampung Barat',          'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Lampung Selatan',        'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Lampung Tengah',         'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Lampung Timur',          'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Lampung Utara',          'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Mesuji',                 'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Pesawaran',              'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Pesisir Barat',          'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Pringsewu',              'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Tanggamus',              'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Tulang Bawang',          'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Tulang Bawang Barat',    'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kabupaten Way Kanan',              'type' => 'KABUPATEN'],
            ['province_code' => '18', 'name' => 'Kota Bandar Lampung',              'type' => 'KOTA'],
            ['province_code' => '18', 'name' => 'Kota Metro',                       'type' => 'KOTA'],
            // 19 Kepulauan Bangka Belitung
            ['province_code' => '19', 'name' => 'Kabupaten Bangka',                 'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kabupaten Bangka Barat',           'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kabupaten Bangka Selatan',         'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kabupaten Bangka Tengah',          'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kabupaten Belitung',               'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kabupaten Belitung Timur',         'type' => 'KABUPATEN'],
            ['province_code' => '19', 'name' => 'Kota Pangkalpinang',               'type' => 'KOTA'],
            // 21 Kepulauan Riau
            ['province_code' => '21', 'name' => 'Kabupaten Bintan',                 'type' => 'KABUPATEN'],
            ['province_code' => '21', 'name' => 'Kabupaten Karimun',                'type' => 'KABUPATEN'],
            ['province_code' => '21', 'name' => 'Kabupaten Kepulauan Anambas',      'type' => 'KABUPATEN'],
            ['province_code' => '21', 'name' => 'Kabupaten Lingga',                 'type' => 'KABUPATEN'],
            ['province_code' => '21', 'name' => 'Kabupaten Natuna',                 'type' => 'KABUPATEN'],
            ['province_code' => '21', 'name' => 'Kota Batam',                       'type' => 'KOTA'],
            ['province_code' => '21', 'name' => 'Kota Tanjungpinang',               'type' => 'KOTA'],
            // 31 DKI Jakarta
            ['province_code' => '31', 'name' => 'Kabupaten Kepulauan Seribu',       'type' => 'KABUPATEN'],
            ['province_code' => '31', 'name' => 'Kota Jakarta Barat',               'type' => 'KOTA'],
            ['province_code' => '31', 'name' => 'Kota Jakarta Pusat',               'type' => 'KOTA'],
            ['province_code' => '31', 'name' => 'Kota Jakarta Selatan',             'type' => 'KOTA'],
            ['province_code' => '31', 'name' => 'Kota Jakarta Timur',               'type' => 'KOTA'],
            ['province_code' => '31', 'name' => 'Kota Jakarta Utara',               'type' => 'KOTA'],
            // 32 Jawa Barat
            ['province_code' => '32', 'name' => 'Kabupaten Bandung',                'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Bandung Barat',          'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Bekasi',                 'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Bogor',                  'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Ciamis',                 'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Cianjur',                'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Cirebon',                'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Garut',                  'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Indramayu',              'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Karawang',               'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Kuningan',               'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Majalengka',             'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Pangandaran',            'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Purwakarta',             'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Subang',                 'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Sukabumi',               'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Sumedang',               'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kabupaten Tasikmalaya',            'type' => 'KABUPATEN'],
            ['province_code' => '32', 'name' => 'Kota Bandung',                     'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Banjar',                      'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Bekasi',                      'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Bogor',                       'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Cimahi',                      'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Cirebon',                     'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Depok',                       'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Sukabumi',                    'type' => 'KOTA'],
            ['province_code' => '32', 'name' => 'Kota Tasikmalaya',                 'type' => 'KOTA'],
            // 33 Jawa Tengah
            ['province_code' => '33', 'name' => 'Kabupaten Banjarnegara',           'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Banyumas',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Batang',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Blora',                  'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Boyolali',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Brebes',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Cilacap',                'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Demak',                  'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Grobogan',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Jepara',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Karanganyar',            'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Kebumen',                'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Kendal',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Klaten',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Kudus',                  'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Magelang',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Pati',                   'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Pekalongan',             'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Pemalang',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Purbalingga',            'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Purworejo',              'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Rembang',                'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Semarang',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Sragen',                 'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Sukoharjo',              'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Tegal',                  'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Temanggung',             'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Wonogiri',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kabupaten Wonosobo',               'type' => 'KABUPATEN'],
            ['province_code' => '33', 'name' => 'Kota Magelang',                    'type' => 'KOTA'],
            ['province_code' => '33', 'name' => 'Kota Pekalongan',                  'type' => 'KOTA'],
            ['province_code' => '33', 'name' => 'Kota Salatiga',                    'type' => 'KOTA'],
            ['province_code' => '33', 'name' => 'Kota Semarang',                    'type' => 'KOTA'],
            ['province_code' => '33', 'name' => 'Kota Surakarta',                   'type' => 'KOTA'],
            ['province_code' => '33', 'name' => 'Kota Tegal',                       'type' => 'KOTA'],
            // 34 DI Yogyakarta
            ['province_code' => '34', 'name' => 'Kabupaten Bantul',                 'type' => 'KABUPATEN'],
            ['province_code' => '34', 'name' => 'Kabupaten Gunungkidul',            'type' => 'KABUPATEN'],
            ['province_code' => '34', 'name' => 'Kabupaten Kulon Progo',            'type' => 'KABUPATEN'],
            ['province_code' => '34', 'name' => 'Kabupaten Sleman',                 'type' => 'KABUPATEN'],
            ['province_code' => '34', 'name' => 'Kota Yogyakarta',                  'type' => 'KOTA'],
            // 35 Jawa Timur
            ['province_code' => '35', 'name' => 'Kabupaten Bangkalan',              'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Banyuwangi',             'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Blitar',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Bojonegoro',             'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Bondowoso',              'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Gresik',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Jember',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Jombang',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Kediri',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Lamongan',               'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Lumajang',               'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Madiun',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Magetan',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Malang',                 'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Mojokerto',              'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Nganjuk',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Ngawi',                  'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Pacitan',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Pamekasan',              'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Pasuruan',               'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Ponorogo',               'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Probolinggo',            'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Sampang',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Sidoarjo',               'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Situbondo',              'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Sumenep',                'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Trenggalek',             'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Tuban',                  'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kabupaten Tulungagung',            'type' => 'KABUPATEN'],
            ['province_code' => '35', 'name' => 'Kota Batu',                        'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Blitar',                      'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Kediri',                      'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Madiun',                      'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Malang',                      'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Mojokerto',                   'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Pasuruan',                    'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Probolinggo',                 'type' => 'KOTA'],
            ['province_code' => '35', 'name' => 'Kota Surabaya',                    'type' => 'KOTA'],
            // 36 Banten
            ['province_code' => '36', 'name' => 'Kabupaten Lebak',                  'type' => 'KABUPATEN'],
            ['province_code' => '36', 'name' => 'Kabupaten Pandeglang',             'type' => 'KABUPATEN'],
            ['province_code' => '36', 'name' => 'Kabupaten Serang',                 'type' => 'KABUPATEN'],
            ['province_code' => '36', 'name' => 'Kabupaten Tangerang',              'type' => 'KABUPATEN'],
            ['province_code' => '36', 'name' => 'Kota Cilegon',                     'type' => 'KOTA'],
            ['province_code' => '36', 'name' => 'Kota Serang',                      'type' => 'KOTA'],
            ['province_code' => '36', 'name' => 'Kota Tangerang',                   'type' => 'KOTA'],
            ['province_code' => '36', 'name' => 'Kota Tangerang Selatan',           'type' => 'KOTA'],
            // 51 Bali
            ['province_code' => '51', 'name' => 'Kabupaten Badung',                 'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Bangli',                 'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Buleleng',               'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Gianyar',                'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Jembrana',               'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Karangasem',             'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Klungkung',              'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kabupaten Tabanan',                'type' => 'KABUPATEN'],
            ['province_code' => '51', 'name' => 'Kota Denpasar',                    'type' => 'KOTA'],
            // 52 NTB
            ['province_code' => '52', 'name' => 'Kabupaten Bima',                   'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Dompu',                  'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Lombok Barat',           'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Lombok Tengah',          'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Lombok Timur',           'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Lombok Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Sumbawa',                'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kabupaten Sumbawa Barat',          'type' => 'KABUPATEN'],
            ['province_code' => '52', 'name' => 'Kota Bima',                        'type' => 'KOTA'],
            ['province_code' => '52', 'name' => 'Kota Mataram',                     'type' => 'KOTA'],
            // 53 NTT
            ['province_code' => '53', 'name' => 'Kabupaten Alor',                   'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Belu',                   'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Ende',                   'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Flores Timur',           'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Kupang',                 'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Lembata',                'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Malaka',                 'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Manggarai',              'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Manggarai Barat',        'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Manggarai Timur',        'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Nagekeo',                'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Ngada',                  'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Rote Ndao',              'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sabu Raijua',            'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sikka',                  'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sumba Barat',            'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sumba Barat Daya',       'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sumba Tengah',           'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Sumba Timur',            'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Timor Tengah Selatan',   'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kabupaten Timor Tengah Utara',     'type' => 'KABUPATEN'],
            ['province_code' => '53', 'name' => 'Kota Kupang',                      'type' => 'KOTA'],
            // 61 Kalimantan Barat
            ['province_code' => '61', 'name' => 'Kabupaten Bengkayang',             'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Kapuas Hulu',            'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Kayong Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Ketapang',               'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Kubu Raya',              'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Landak',                 'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Melawi',                 'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Mempawah',               'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Sambas',                 'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Sanggau',                'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Sekadau',                'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kabupaten Sintang',                'type' => 'KABUPATEN'],
            ['province_code' => '61', 'name' => 'Kota Pontianak',                   'type' => 'KOTA'],
            ['province_code' => '61', 'name' => 'Kota Singkawang',                  'type' => 'KOTA'],
            // 62 Kalimantan Tengah
            ['province_code' => '62', 'name' => 'Kabupaten Barito Selatan',         'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Barito Timur',           'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Barito Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Gunung Mas',             'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Kapuas',                 'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Katingan',               'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Kotawaringin Barat',     'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Kotawaringin Timur',     'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Lamandau',               'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Murung Raya',            'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Pulang Pisau',           'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Seruyan',                'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kabupaten Sukamara',               'type' => 'KABUPATEN'],
            ['province_code' => '62', 'name' => 'Kota Palangka Raya',               'type' => 'KOTA'],
            // 63 Kalimantan Selatan
            ['province_code' => '63', 'name' => 'Kabupaten Balangan',               'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Banjar',                 'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Barito Kuala',           'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Hulu Sungai Selatan',    'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Hulu Sungai Tengah',     'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Hulu Sungai Utara',      'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Kota Baru',              'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Tabalong',               'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Tanah Bumbu',            'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Tanah Laut',             'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kabupaten Tapin',                  'type' => 'KABUPATEN'],
            ['province_code' => '63', 'name' => 'Kota Banjarbaru',                  'type' => 'KOTA'],
            ['province_code' => '63', 'name' => 'Kota Banjarmasin',                 'type' => 'KOTA'],
            // 64 Kalimantan Timur
            ['province_code' => '64', 'name' => 'Kabupaten Berau',                  'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Kutai Barat',            'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Kutai Kartanegara',      'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Kutai Timur',            'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Mahakam Ulu',            'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Paser',                  'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kabupaten Penajam Paser Utara',    'type' => 'KABUPATEN'],
            ['province_code' => '64', 'name' => 'Kota Balikpapan',                  'type' => 'KOTA'],
            ['province_code' => '64', 'name' => 'Kota Bontang',                     'type' => 'KOTA'],
            ['province_code' => '64', 'name' => 'Kota Samarinda',                   'type' => 'KOTA'],
            // 65 Kalimantan Utara
            ['province_code' => '65', 'name' => 'Kabupaten Bulungan',               'type' => 'KABUPATEN'],
            ['province_code' => '65', 'name' => 'Kabupaten Malinau',                'type' => 'KABUPATEN'],
            ['province_code' => '65', 'name' => 'Kabupaten Nunukan',                'type' => 'KABUPATEN'],
            ['province_code' => '65', 'name' => 'Kabupaten Tana Tidung',            'type' => 'KABUPATEN'],
            ['province_code' => '65', 'name' => 'Kota Tarakan',                     'type' => 'KOTA'],
            // 71 Sulawesi Utara
            ['province_code' => '71', 'name' => 'Kabupaten Bolaang Mongondow',              'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Bolaang Mongondow Selatan',      'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Bolaang Mongondow Timur',        'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Bolaang Mongondow Utara',        'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Kepulauan Sangihe',              'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro','type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Kepulauan Talaud',               'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Minahasa',                       'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Minahasa Selatan',               'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Minahasa Tenggara',              'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kabupaten Minahasa Utara',                 'type' => 'KABUPATEN'],
            ['province_code' => '71', 'name' => 'Kota Bitung',                              'type' => 'KOTA'],
            ['province_code' => '71', 'name' => 'Kota Kotamobagu',                          'type' => 'KOTA'],
            ['province_code' => '71', 'name' => 'Kota Manado',                              'type' => 'KOTA'],
            ['province_code' => '71', 'name' => 'Kota Tomohon',                             'type' => 'KOTA'],
            // 72 Sulawesi Tengah
            ['province_code' => '72', 'name' => 'Kabupaten Banggai',                'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Banggai Kepulauan',      'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Banggai Laut',           'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Buol',                   'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Donggala',               'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Morowali',               'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Morowali Utara',         'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Parigi Moutong',         'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Poso',                   'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Sigi',                   'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Tojo Una-Una',           'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kabupaten Toli-Toli',              'type' => 'KABUPATEN'],
            ['province_code' => '72', 'name' => 'Kota Palu',                        'type' => 'KOTA'],
            // 73 Sulawesi Selatan
            ['province_code' => '73', 'name' => 'Kabupaten Bantaeng',               'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Barru',                  'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Bone',                   'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Bulukumba',              'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Enrekang',               'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Gowa',                   'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Jeneponto',              'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Kepulauan Selayar',      'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Luwu',                   'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Luwu Timur',             'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Luwu Utara',             'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Maros',                  'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Pangkajene dan Kepulauan','type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Pinrang',                'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Sidenreng Rappang',      'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Sinjai',                 'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Soppeng',                'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Takalar',                'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Tana Toraja',            'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Toraja Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kabupaten Wajo',                   'type' => 'KABUPATEN'],
            ['province_code' => '73', 'name' => 'Kota Makassar',                    'type' => 'KOTA'],
            ['province_code' => '73', 'name' => 'Kota Palopo',                      'type' => 'KOTA'],
            ['province_code' => '73', 'name' => 'Kota Parepare',                    'type' => 'KOTA'],
            // 74 Sulawesi Tenggara
            ['province_code' => '74', 'name' => 'Kabupaten Bombana',                'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Buton',                  'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Buton Selatan',          'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Buton Tengah',           'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Buton Utara',            'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Kolaka',                 'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Kolaka Timur',           'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Kolaka Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Konawe',                 'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Konawe Kepulauan',       'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Konawe Selatan',         'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Konawe Utara',           'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Muna',                   'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Muna Barat',             'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kabupaten Wakatobi',               'type' => 'KABUPATEN'],
            ['province_code' => '74', 'name' => 'Kota Baubau',                      'type' => 'KOTA'],
            ['province_code' => '74', 'name' => 'Kota Kendari',                     'type' => 'KOTA'],
            // 75 Gorontalo
            ['province_code' => '75', 'name' => 'Kabupaten Boalemo',                'type' => 'KABUPATEN'],
            ['province_code' => '75', 'name' => 'Kabupaten Bone Bolango',           'type' => 'KABUPATEN'],
            ['province_code' => '75', 'name' => 'Kabupaten Gorontalo',              'type' => 'KABUPATEN'],
            ['province_code' => '75', 'name' => 'Kabupaten Gorontalo Utara',        'type' => 'KABUPATEN'],
            ['province_code' => '75', 'name' => 'Kabupaten Pohuwato',               'type' => 'KABUPATEN'],
            ['province_code' => '75', 'name' => 'Kota Gorontalo',                   'type' => 'KOTA'],
            // 76 Sulawesi Barat
            ['province_code' => '76', 'name' => 'Kabupaten Majene',                 'type' => 'KABUPATEN'],
            ['province_code' => '76', 'name' => 'Kabupaten Mamasa',                 'type' => 'KABUPATEN'],
            ['province_code' => '76', 'name' => 'Kabupaten Mamuju',                 'type' => 'KABUPATEN'],
            ['province_code' => '76', 'name' => 'Kabupaten Mamuju Tengah',          'type' => 'KABUPATEN'],
            ['province_code' => '76', 'name' => 'Kabupaten Pasangkayu',             'type' => 'KABUPATEN'],
            ['province_code' => '76', 'name' => 'Kabupaten Polewali Mandar',        'type' => 'KABUPATEN'],
            // 81 Maluku
            ['province_code' => '81', 'name' => 'Kabupaten Buru',                   'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Buru Selatan',           'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Kepulauan Aru',          'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Kepulauan Tanimbar',     'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Maluku Barat Daya',      'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Maluku Tengah',          'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Maluku Tenggara',        'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Seram Bagian Barat',     'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kabupaten Seram Bagian Timur',     'type' => 'KABUPATEN'],
            ['province_code' => '81', 'name' => 'Kota Ambon',                       'type' => 'KOTA'],
            ['province_code' => '81', 'name' => 'Kota Tual',                        'type' => 'KOTA'],
            // 82 Maluku Utara
            ['province_code' => '82', 'name' => 'Kabupaten Halmahera Barat',        'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Halmahera Selatan',      'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Halmahera Tengah',       'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Halmahera Timur',        'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Halmahera Utara',        'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Kepulauan Sula',         'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Pulau Morotai',          'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kabupaten Pulau Taliabu',          'type' => 'KABUPATEN'],
            ['province_code' => '82', 'name' => 'Kota Ternate',                     'type' => 'KOTA'],
            ['province_code' => '82', 'name' => 'Kota Tidore Kepulauan',            'type' => 'KOTA'],
            // 91 Papua Barat
            ['province_code' => '91', 'name' => 'Kabupaten Fakfak',                 'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Kaimana',                'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Manokwari',              'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Manokwari Selatan',      'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Pegunungan Arfak',       'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Teluk Bintuni',          'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kabupaten Teluk Wondama',          'type' => 'KABUPATEN'],
            ['province_code' => '91', 'name' => 'Kota Manokwari',                   'type' => 'KOTA'],
            // 94 Papua
            ['province_code' => '94', 'name' => 'Kabupaten Biak Numfor',            'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Jayapura',               'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Keerom',                 'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Kepulauan Yapen',        'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Mamberamo Raya',         'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Sarmi',                  'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Supiori',                'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kabupaten Waropen',                'type' => 'KABUPATEN'],
            ['province_code' => '94', 'name' => 'Kota Jayapura',                    'type' => 'KOTA'],
            // 95 Papua Selatan
            ['province_code' => '95', 'name' => 'Kabupaten Asmat',                  'type' => 'KABUPATEN'],
            ['province_code' => '95', 'name' => 'Kabupaten Boven Digoel',           'type' => 'KABUPATEN'],
            ['province_code' => '95', 'name' => 'Kabupaten Mappi',                  'type' => 'KABUPATEN'],
            ['province_code' => '95', 'name' => 'Kabupaten Merauke',                'type' => 'KABUPATEN'],
            // 96 Papua Tengah
            ['province_code' => '96', 'name' => 'Kabupaten Deiyai',                 'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Dogiyai',                'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Intan Jaya',             'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Mimika',                 'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Nabire',                 'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Paniai',                 'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Puncak',                 'type' => 'KABUPATEN'],
            ['province_code' => '96', 'name' => 'Kabupaten Puncak Jaya',            'type' => 'KABUPATEN'],
            // 97 Papua Pegunungan
            ['province_code' => '97', 'name' => 'Kabupaten Jayawijaya',             'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Lanny Jaya',             'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Mamberamo Tengah',       'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Nduga',                  'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Pegunungan Bintang',     'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Tolikara',               'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Yahukimo',               'type' => 'KABUPATEN'],
            ['province_code' => '97', 'name' => 'Kabupaten Yalimo',                 'type' => 'KABUPATEN'],
            // 98 Papua Barat Daya
            ['province_code' => '98', 'name' => 'Kabupaten Maybrat',                'type' => 'KABUPATEN'],
            ['province_code' => '98', 'name' => 'Kabupaten Raja Ampat',             'type' => 'KABUPATEN'],
            ['province_code' => '98', 'name' => 'Kabupaten Sorong',                 'type' => 'KABUPATEN'],
            ['province_code' => '98', 'name' => 'Kabupaten Sorong Selatan',         'type' => 'KABUPATEN'],
            ['province_code' => '98', 'name' => 'Kabupaten Tambrauw',               'type' => 'KABUPATEN'],
            ['province_code' => '98', 'name' => 'Kota Sorong',                      'type' => 'KOTA'],
        ];

        DB::table('cities')->insertOrIgnore($cities);
    }
}